// EAS
export const chainId = 1301;
export const SCHEMA_ID_EAS =
  '0x406423b9d5dce47cc47cf83ac566b1252129fd6b6d9e1ca82a7153c7a70477ce';
export const SCHEMA_ID_SIGN = 'SPS_SCSmqhMkeyCD8-nES92lz';

export const schema =
  'uint16 commitsCount, uint16 commitProportion, uint16 normalizedContributors, uint16 contributionRecency, uint16 normalizedTx, uint16 normalizedUniqueFrom, uint16 normalizedTve';
export const easSchemaRegistryContractAddress =
  '0x7725E06Fb7eBa21e5081604C6D0328Db18428027';
export const easContractAddress = '0xB33e25FCA2724F332B42d3bF2Baa105878889B41';

// Reputation Model
export const COMMIT_RANGE_0_10 = '0-10';
export const COMMIT_RANGE_10_30 = '10-30';
export const COMMIT_RANGE_30_PLUS = '30+';

const CONTRIBUTORS_WEIGHT = {
  COMMIT_WEIGHT: 30,
  NB_OF_CONTRIBUTOR_WEIGHT: 10,
  CONTRIBUTION_RECENCY: {
    RECENT_CONTRIBUTION_WEIGHT: 10, // less than 3 month
    MID_TERM_CONTRIBUTION_WEIGHT: 5, // less than 1 year
    LONG_TERM_CONTRIBUTION_WEIGHT: 1, // More
  },
  TX_WEIGHT: 10,
  UNIQUE_FROM_WEIGHT: 10,
  TVE_WEIGHT: 30,
};

export const CONTRIBUTORS_WEIGHT_MATRIX = {
  [COMMIT_RANGE_0_10]: {
    COMMIT_WEIGHT: CONTRIBUTORS_WEIGHT.COMMIT_WEIGHT / 10,
    NB_OF_CONTRIBUTOR_WEIGHT: CONTRIBUTORS_WEIGHT.NB_OF_CONTRIBUTOR_WEIGHT / 10,
    CONTRIBUTION_RECENCY: {
      RECENT_CONTRIBUTION_WEIGHT:
        CONTRIBUTORS_WEIGHT.CONTRIBUTION_RECENCY.RECENT_CONTRIBUTION_WEIGHT /
        10,
      MID_TERM_CONTRIBUTION_WEIGHT:
        CONTRIBUTORS_WEIGHT.CONTRIBUTION_RECENCY.MID_TERM_CONTRIBUTION_WEIGHT /
        10,
      LONG_TERM_CONTRIBUTION_WEIGHT:
        CONTRIBUTORS_WEIGHT.CONTRIBUTION_RECENCY.LONG_TERM_CONTRIBUTION_WEIGHT /
        10,
    },
    TX_WEIGHT: CONTRIBUTORS_WEIGHT.TX_WEIGHT / 10,
    UNIQUE_FROM_WEIGHT: CONTRIBUTORS_WEIGHT.UNIQUE_FROM_WEIGHT / 10,
    TVE_WEIGHT: CONTRIBUTORS_WEIGHT.TVE_WEIGHT / 10,
  },
  [COMMIT_RANGE_10_30]: {
    COMMIT_WEIGHT: CONTRIBUTORS_WEIGHT.COMMIT_WEIGHT / 2,
    NB_OF_CONTRIBUTOR_WEIGHT: CONTRIBUTORS_WEIGHT.NB_OF_CONTRIBUTOR_WEIGHT / 2,
    CONTRIBUTION_RECENCY: {
      RECENT_CONTRIBUTION_WEIGHT:
        CONTRIBUTORS_WEIGHT.CONTRIBUTION_RECENCY.RECENT_CONTRIBUTION_WEIGHT / 2,
      MID_TERM_CONTRIBUTION_WEIGHT:
        CONTRIBUTORS_WEIGHT.CONTRIBUTION_RECENCY.MID_TERM_CONTRIBUTION_WEIGHT /
        2,
      LONG_TERM_CONTRIBUTION_WEIGHT:
        CONTRIBUTORS_WEIGHT.CONTRIBUTION_RECENCY.LONG_TERM_CONTRIBUTION_WEIGHT /
        2,
    },
    TX_WEIGHT: CONTRIBUTORS_WEIGHT.TX_WEIGHT / 2,
    UNIQUE_FROM_WEIGHT: CONTRIBUTORS_WEIGHT.UNIQUE_FROM_WEIGHT / 2,
    TVE_WEIGHT: CONTRIBUTORS_WEIGHT.TVE_WEIGHT / 2,
  },
  [COMMIT_RANGE_30_PLUS]: {
    COMMIT_WEIGHT: CONTRIBUTORS_WEIGHT.COMMIT_WEIGHT,
    NB_OF_CONTRIBUTOR_WEIGHT: CONTRIBUTORS_WEIGHT.NB_OF_CONTRIBUTOR_WEIGHT,
    CONTRIBUTION_RECENCY: {
      RECENT_CONTRIBUTION_WEIGHT:
        CONTRIBUTORS_WEIGHT.CONTRIBUTION_RECENCY.RECENT_CONTRIBUTION_WEIGHT,
      MID_TERM_CONTRIBUTION_WEIGHT:
        CONTRIBUTORS_WEIGHT.CONTRIBUTION_RECENCY.MID_TERM_CONTRIBUTION_WEIGHT,
      LONG_TERM_CONTRIBUTION_WEIGHT:
        CONTRIBUTORS_WEIGHT.CONTRIBUTION_RECENCY.LONG_TERM_CONTRIBUTION_WEIGHT,
    },
    TX_WEIGHT: CONTRIBUTORS_WEIGHT.TX_WEIGHT,
    UNIQUE_FROM_WEIGHT: CONTRIBUTORS_WEIGHT.UNIQUE_FROM_WEIGHT,
    TVE_WEIGHT: CONTRIBUTORS_WEIGHT.TVE_WEIGHT,
  },
};

export const ORGANIZATION_WEIGHT_MATRIX = {
  PROTOCOL_WEIGHT: 0.55,
  CONTRIBUTORS_WEIGHT: 0.45,
  CONTRIBUTION_RECENCY: {
    RECENT_CONTRIBUTION_WEIGHT: 30,
    MID_TERM_CONTRIBUTION_WEIGHT: 7,
    LONG_TERM_CONTRIBUTION_WEIGHT: 3,
  },
  NB_OF_CONTRIBUTOR_WEIGHT: 5,
  NB_OF_REPOSITORY_WEIGHT: 5,
  TX_WEIGHT: 15,
  UNIQUE_FROM_WEIGHT: 15,
  TVE_WEIGHT: 30,
};
