name: reputation-model-ui

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_CEDRIC_TEAM_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_REPUTATION_MODEL_UI_PROJECT_ID }}

on:
  push:
    paths:
      - "packages/reputation-model-ui/**"
      - ".github/workflows/reputation-model-ui.yml"
      - '!**/README.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: packages/reputation-model-ui

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        node -v
        npm -v
        npm ci

    - name: Vercel deploy to prod
      run: |
        npm install --global vercel@latest
        vercel pull --yes --environment=production --token=${{ secrets.VERCEL_CEDRIC_TOKEN }}
        vercel build --prod --token=${{ secrets.VERCEL_CEDRIC_TOKEN }}
        vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_CEDRIC_TOKEN }}
